name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run Docker image from Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: koka-image:latest
          
      - name: Run tests in container
        run: docker run --rm koka-image:latest koka -e testcombined.kk